name: Cgenial

dependencies:
  - python=3.9
  - pip
  - pip:
    - folium
    - osmnx
    - pandas
    - geopandas
    - matplotlib
    - wikipedia
    #- streamlit-extras
    - mapclassify
    - streamlit-folium
